# Generated by Django 3.1 on 2020-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200830_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
