# Generated by Django 3.1 on 2020-08-30 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200830_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
